version: '3.0'
services:
  database:
    image: 'postgres:16'
    container_name: task-tracker-core-db
    environment:
      - 'POSTGRES_DB=${DB_URL:-task_tracker_db}'
      - 'POSTGRES_USER=${DB_USER:-admin}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD:-admin}'
    ports:
      - '5436:5432'